Repository Universite-Gustave-Eiffel/NoiseCaptureClient, pull requests merged in 2024-07, with the labels that each got.

#17 Feature/build ios
  .github/pull_request_template.md
  .github/workflows/test.yml
  androidApp/build.gradle.kts
  androidApp/src/main/kotlin/org/noise_planet/noisecapture/starter/MainActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
  ios/ios.podspec
  ios/src/iosMain/kotlin/main.ios.kt
  iosApp/Podfile.lock
  iosApp/Pods/Local Podspecs/ios.podspec.json
  iosApp/Pods/Manifest.lock
  iosApp/Pods/Pods.xcodeproj/project.pbxproj
  iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources-Debug-input-files.xcfilelist
  iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources-Release-input-files.xcfilelist
  iosApp/Pods/Target Support Files/Pods-iosApp/Pods-iosApp-resources.sh
  iosApp/iosApp.xcodeproj/project.pbxproj
  shared/build.gradle.kts
  shared/src/commonMain/kotlin/org/noise_planet/noisecapture/shared/child/HomeScreen.kt
  shared/src/commonMain/kotlin/org/noise_planet/noisecapture/shared/child/MeasurementScreen.kt
  shared/src/commonMain/kotlin/org/noise_planet/noisecapture/shared/child/NavigationScreen.kt
  shared/src/commonMain/kotlin/org/noise_planet/noisecapture/shared/child/PermissionScreen.kt
  shared/src/commonMain/kotlin/org/noise_planet/noisecapture/shared/root/RootNode.kt
  shared/src/commonTest/composeResources/files/config_48000_third_octave.json
  shared/src/commonTest/composeResources/files/speak_44100Hz_16bitsPCM_10s.raw
  shared/src/commonTest/kotlin/org/noise_planet/noisecapture/shared/signal/SpectrumChannelTest.kt
  webApp/src/jsMain/kotlin/Main.kt
Labels: KMP, iOS

#19 Update readme with funding from Sonoreze
  README.md
Labels: documentation

#20 Fix android version, add android compile into testing
  .github/workflows/test.yml
  gradle/libs.versions.toml
Labels: KMP, Android

#22 Update README.md
  README.md
Labels: documentation
